### ISSUE TITLE
Perceptual Speed Index

### ISSUE THREAD

**Issue by paulirish** [pmdartus/speedline#19]
FYI pat meenan now has a standalone project for calculating metrics like this: https://github.com/WPO-Foundation/visualmetrics

It includes perceptual speed index; https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L820-L855

While SI uses color distribution to compare two frames, perSI uses [SSIM](https://en.wikipedia.org/wiki/Structural_similarity) instead.

What do you think about doing the same here in speedline? [image-ssim](https://github.com/darosh/image-ssim-js) looks very well done. Hmm!

**Comment by pmdartus** [comment]
That's a great idea. I tried to implement the perSI with the image-ssim, unfortunately the results were not great. I think it worth giving another shot!

**Comment by pmdartus** [comment]
I have started to implement it on #20
I used the same approach, however the perceived speed index value is really different from the standard approach value. This is due to the fact that the visual progress of the first frame is not 0.

<img width="531" alt="screen shot 2016-05-16 at 11 20 53" src="https://cloud.githubusercontent.com/assets/2567083/15285732/65fcc120-1b59-11e6-8ad6-56b1cf0c30e5.png">

I think that we should remap the value from 0 to 100 if we want to compare the standard and the perceived approach. It doesn't seams that [visualmetric](https://github.com/WPO-Foundation/visualmetrics/blob/master/visualmetrics.py#L838) is doing this.

@paulirish What do you think ?
