### ISSUE TITLE
GraphicsMagick or ImageMagick?

### ISSUE THREAD

**Issue by paulirish** [pmdartus/speedline#6]
The readme says IM must be installed, but the module depends on the GM module. 

I'm just confused on this. Is there a fallback layer in between?

**Comment by paulirish** [comment]
@samccone and I looked at this a little closer. We're generally very happy with the source, though have a few questions.

We have an interest in using speedline inside of https://github.com/GoogleChrome/lighthouse/ which is browserified for one of our deployments. Is there a hard dependency on image/graphicsmagick for this buffer? We'd love if speedline was easily browserifyable.

cc @samthor

**Comment by pmdartus** [comment]
I wasn't planning to use ImageMagick at the beginning, but I was facing issues when extracting the screenshots from timeline. The [get-pixel](https://www.npmjs.com/package/get-pixels) module is not able to parse the PNG. That's why I introduce an [extra step](https://github.com/pmdartus/speedline/blob/17d37efa18adffec82917239681a5d995137c77d/src/frame.js#L64) where I use ImageMagick to convert each png in jpg before reloading them in memory. I faced the same issue for [snapline](https://github.com/pmdartus/snapline).

By the way great job for lighthouse, I am looking closely at the project since it's early days. 😉

**Comment by samccone** [comment]
Seems like this module *might* be able to do what you want 💃 
https://www.npmjs.com/package/pngjs2

**Comment by paulirish** [comment]
I have a fix. Even easier.  

PR incoming
